/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TeoriaDeConjuntosDefinidos;

import TeoriaDeConjuntos.*;
import clases.AgregarConjuntoA;
import clases.AgregarConjuntoB;
import static clases.AuB.Unir;
import clases.AxB;
import clases.Sub;
import clases.SubPropio;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian AC
 */
public class AplicarTeoríaConjuntosDefinidos extends javax.swing.JFrame {

    /**
     * Creates new form AplicarTeoríacreandoConjuntos
     */
    public AplicarTeoríaConjuntosDefinidos() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioDefinido = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aInterseccionB = new javax.swing.JMenu();
        crearA = new javax.swing.JMenuItem();
        crearB = new javax.swing.JMenuItem();
        nElementoConjunto = new javax.swing.JMenuItem();
        aUnionB = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        aMenosB = new javax.swing.JMenuItem();
        bMenosA = new javax.swing.JMenuItem();
        aSubB = new javax.swing.JMenuItem();
        bSubA = new javax.swing.JMenuItem();
        aSubPropiob = new javax.swing.JMenuItem();
        bSubPropiaa = new javax.swing.JMenuItem();
        aPorB = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        atras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicar la teoria de conjuntos definidos");
        setUndecorated(true);

        EscritorioDefinido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EscritorioDefinidoLayout = new javax.swing.GroupLayout(EscritorioDefinido);
        EscritorioDefinido.setLayout(EscritorioDefinidoLayout);
        EscritorioDefinidoLayout.setHorizontalGroup(
            EscritorioDefinidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        EscritorioDefinidoLayout.setVerticalGroup(
            EscritorioDefinidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        aInterseccionB.setBackground(new java.awt.Color(255, 255, 255));
        aInterseccionB.setText("Opciones");

        crearA.setText("Crear Conjunto A ");
        crearA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAActionPerformed(evt);
            }
        });
        aInterseccionB.add(crearA);

        crearB.setText("Crear Conjunto B ");
        crearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBActionPerformed(evt);
            }
        });
        aInterseccionB.add(crearB);

        nElementoConjunto.setText("Número de Elementos del Conjunto ");
        nElementoConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nElementoConjuntoActionPerformed(evt);
            }
        });
        aInterseccionB.add(nElementoConjunto);

        aUnionB.setText("Realizar A U B ");
        aUnionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aUnionBActionPerformed(evt);
            }
        });
        aInterseccionB.add(aUnionB);

        jMenuItem1.setText("Realizar A ᴖ B ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        aInterseccionB.add(jMenuItem1);

        aMenosB.setText("Realizar A - B ");
        aMenosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenosBActionPerformed(evt);
            }
        });
        aInterseccionB.add(aMenosB);

        bMenosA.setText("Realizar B - A ");
        bMenosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosAActionPerformed(evt);
            }
        });
        aInterseccionB.add(bMenosA);

        aSubB.setText("Definir si A es Subconjunto de B ");
        aSubB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSubBActionPerformed(evt);
            }
        });
        aInterseccionB.add(aSubB);

        bSubA.setText("Definir si B es Subconjunto de A ");
        bSubA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubAActionPerformed(evt);
            }
        });
        aInterseccionB.add(bSubA);

        aSubPropiob.setText("Definir si A es subconjunto propio de B");
        aSubPropiob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSubPropiobActionPerformed(evt);
            }
        });
        aInterseccionB.add(aSubPropiob);

        bSubPropiaa.setText("Definir si B es subconjunto propio de A ");
        bSubPropiaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubPropiaaActionPerformed(evt);
            }
        });
        aInterseccionB.add(bSubPropiaa);

        aPorB.setText("Producto Cartesiano de A X B ");
        aPorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPorBActionPerformed(evt);
            }
        });
        aInterseccionB.add(aPorB);

        jMenuBar1.add(aInterseccionB);

        jMenu2.setText("Atras");

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jMenu2.add(atras);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscritorioDefinido)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscritorioDefinido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aUnionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aUnionBActionPerformed
        if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            UnionDefinidos union = new UnionDefinidos();
            EscritorioDefinido.add(union);
            union.show();
        }
    }//GEN-LAST:event_aUnionBActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            InterseccionDefinido interseccion = new InterseccionDefinido();
            EscritorioDefinido.add(interseccion);
            interseccion.show();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void aMenosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMenosBActionPerformed
              if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            AdiferenciaBDefinido AmenosB = new AdiferenciaBDefinido();
            EscritorioDefinido.add(AmenosB);
           AmenosB.show();
        }
    }//GEN-LAST:event_aMenosBActionPerformed

    private void bMenosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosAActionPerformed
               if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
             BdiferenciaADefinido BmenosA = new BdiferenciaADefinido();
            EscritorioDefinido.add(BmenosA);
           BmenosA.show();
        }
    }//GEN-LAST:event_bMenosAActionPerformed

    private void aSubBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSubBActionPerformed
   if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Es: " + SubDefinido.ASubB(), "A su conjunto de B", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_aSubBActionPerformed

    private void bSubAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubAActionPerformed
       if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Es: " + SubDefinido.BSubA(), "B su conjunto de A", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSubAActionPerformed

    private void aPorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPorBActionPerformed
        if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            ProductoCartesianoDefinido AporB = new ProductoCartesianoDefinido();
            EscritorioDefinido.add(AporB);
           AporB.show();
        }
    }//GEN-LAST:event_aPorBActionPerformed

    private void aSubPropiobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSubPropiobActionPerformed
      if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Es: " + SubPropioDefinido.ASubPropioB(), " A subconjunto propio  de B", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_aSubPropiobActionPerformed

    private void bSubPropiaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubPropiaaActionPerformed
        if (CrearConjutoADefinido.conjuntoADefinido.isEmpty() || CrearConjutoBDefinido.conjuntoBDefinido.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha creado ningun conjunto", "Aviso¡", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Es: " + SubPropioDefinido.BSubPropioA(), " B subconjunto propio  de A", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSubPropiaaActionPerformed

    private void nElementoConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nElementoConjuntoActionPerformed
        CrearConjutoADefinido.contA();
        CrearConjutoBDefinido.contB();
    }//GEN-LAST:event_nElementoConjuntoActionPerformed

    private void crearAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAActionPerformed
        CrearConjuntoADefinido jFrame = new CrearConjuntoADefinido();
        jFrame.setVisible(true);
    }//GEN-LAST:event_crearAActionPerformed

    private void crearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBActionPerformed
        CrearConjuntoBDefinido jFrame = new CrearConjuntoBDefinido();
        jFrame.setVisible(true);
    }//GEN-LAST:event_crearBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicarTeoríaConjuntosDefinidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioDefinido;
    private javax.swing.JMenu aInterseccionB;
    private javax.swing.JMenuItem aMenosB;
    private javax.swing.JMenuItem aPorB;
    private javax.swing.JMenuItem aSubB;
    private javax.swing.JMenuItem aSubPropiob;
    private javax.swing.JMenuItem aUnionB;
    private javax.swing.JMenuItem atras;
    private javax.swing.JMenuItem bMenosA;
    private javax.swing.JMenuItem bSubA;
    private javax.swing.JMenuItem bSubPropiaa;
    private javax.swing.JMenuItem crearA;
    private javax.swing.JMenuItem crearB;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem nElementoConjunto;
    // End of variables declaration//GEN-END:variables
}
